// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYi4kxXyFZ9iGSlhsZEW3LEpNNBajVi_0',
    appId: '1:685913601220:web:ce0a1fd5f1f87bb36f0591',
    messagingSenderId: '685913601220',
    projectId: 'finalprojectbizconnect',
    authDomain: 'finalprojectbizconnect.firebaseapp.com',
    storageBucket: 'finalprojectbizconnect.firebasestorage.app',
    measurementId: 'G-SQFG8VZ6C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm9M0S-TD_YBMz14ltYtQbgHTNX_Ze5Zw',
    appId: '1:685913601220:android:e9ed179c34b4196b6f0591',
    messagingSenderId: '685913601220',
    projectId: 'finalprojectbizconnect',
    storageBucket: 'finalprojectbizconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmOUUM2fdUoT8Wr8eM6tZ5CWPagAtKq4',
    appId: '1:685913601220:ios:722aacbb09ed6c916f0591',
    messagingSenderId: '685913601220',
    projectId: 'finalprojectbizconnect',
    storageBucket: 'finalprojectbizconnect.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectBizconnectApplicationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmOUUM2fdUoT8Wr8eM6tZ5CWPagAtKq4',
    appId: '1:685913601220:ios:722aacbb09ed6c916f0591',
    messagingSenderId: '685913601220',
    projectId: 'finalprojectbizconnect',
    storageBucket: 'finalprojectbizconnect.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectBizconnectApplicationDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYi4kxXyFZ9iGSlhsZEW3LEpNNBajVi_0',
    appId: '1:685913601220:web:036e037ad970ff5d6f0591',
    messagingSenderId: '685913601220',
    projectId: 'finalprojectbizconnect',
    authDomain: 'finalprojectbizconnect.firebaseapp.com',
    storageBucket: 'finalprojectbizconnect.firebasestorage.app',
    measurementId: 'G-CY6MQJHLZ3',
  );
}
